### ISSUE TITLE
Camelize doesn't seem to work as I expected.

### ISSUE THREAD

**Issue by martyphee** [rails/jbuilder#236]
I have a Jbuilder template like so

```
json.contract @contract
```

Then in my application.rb I have
```
Jbuilder.key_format camelize: :lower
```

What I get back is regular ruby style.  
```json
{"contract":{"commission_includes_tax":true,"commission_tax":"0.0","cycle_days":20,"effective_date":"2011-01-01","end_date":"9999-01-01","free_trial_days":0,"id":1,"restaurant_id":1,"signed_date":"2011-01-01"}}
```

I expected the object to come back camelized.  

If I include the field individually then I get back what I was expecting.  Is there a way to configure it to output an object's fields in camelcase?

**Comment by rwz** [comment]
That's weird. I can't recreate that behavior.

```
[1] pry(main)> Jbuilder.key_format camelize: :lower
=> #<Jbuilder::KeyFormatter:0x007fefcab2ff40 @cache={}, @format={:camelize=>:lower}>
[2] pry(main)> Jbuilder.encode{ |json| json.commission_includes_tax true }
=> "{\"commissionIncludesTax\":true}"
```

Are you sure you're not overriding `key_format` in the template? If not, could you provide a showcase app exposing this behavior?

**Comment by martyphee** [comment]
Definitely not using it anywhere else.  I just found it.

I will revisit and see what I'm doing wrong then.

**Comment by mczepiel** [comment]
I am experiencing the same issue, in an initializer I have
```ruby
Jbuilder.key_format camelize: :lower
```

This is applied correctly to keys explicitly listed in the template:
```ruby
json.my_people @people
```

But not to the keys on `@people`

```json
"myPeople": [
{
"id": 1,
"name": "Alice",
"created_at" : "..."
```

Notice "myPeople" is as I specified, but "createdAt" is not

**Comment by rwz** [comment]
@mczepiel the code that you posted doesn't rely on Jbuilder to build json. It essentially does `@people.to_json` and completely bypasses Jbuilder API therefore camelize transformation is not applied.

In order for camelize to work, use Jbuilder's API.

**Comment by mczepiel** [comment]
Ah, I was under the impression that since I was in a jbuilder template the default behavior would be to use jbuilder's serialization and not use `to_json`.

I will say I outgrew this issue once I started explicitly listing keys, (i.e. using the jbuilder API as you've suggested) but when I was just getting started I was using this as a way to preview the response with the default properties and was surprised it didn't adhere to the specified key format, as was the original reporter.

Would be nice if it overrode the key formatting of `to_json` when used in this context but I suppose that would have let me be lazy for too long an the behavior is understandable, if not immediately obvious.

**Comment by chrisnicola** [comment]
How are you supposed to handle this in situations where the keys are dynamic though. Such as serializing errors?

**Comment by chrisnicola** [comment]
I see it's actually  mentioned in the Readme, just not immediately obvious. Something like this works:
```
json.errors do
  errors.each do |attr, message|
    json.set! attr, message
  end
end
json.error_messages errors.full_messages
```
