### ISSUE TITLE
ActionView::Template::Error (no implicit conversion of String into Integer)

### ISSUE THREAD

**Issue by dougfarre** [rails/jbuilder#247]
Here is my index.json.jbuilder
```
json.array! @destinations do |destination|
  json.partial! 'destination', destination: destination
end

json.helpers do
  json.static_string "string"
end
```

Error: ActionView::Template::Error (no implicit conversion of String into Integer): on line 6.

I've also tried taking the `json.static_string` statement out of a block. I've been struggling with this bug for a while now.

```
jbuilder (2.2.5)
  activesupport (>= 3.0.0, < 5)
  multi_json (~> 1.2)

rails (4.1.8)
  actionmailer (= 4.1.8)
  actionpack (= 4.1.8)
  actionview (= 4.1.8)
```
If i remove the `json.helpers` block, everything is fine.  Also, this only seems to be an issue when adding onto an index controller action view... If thats even possible.

The response from the server is an empty array (because @destinations is empty).

**Comment by dougfarre** [comment]
Solution.  The son.array line needs to be wrapped in a block!

**Comment by rwz** [comment]
Well, look. After you run

```ruby
json.array! @destinations
```

your structure is an array of destinations:
```json
[{ "id": 1 }, { "id": 2 }]
```

and now you're trying to add a key called `helpers`. To an Array. JSON doesn't support key-values in arrays. So the code you're trying to execute doesn't make sense.

The problem here is that the error message clearly fails to communicate the real reason it's blowing up. This could definitely be improved.

**Comment by rwz** [comment]
I've created a new issue https://github.com/rails/jbuilder/issues/248 to address this problem. Thanks for reporting :)

**Comment by dinkengraven** [comment]
Just ran into this same problem and found this conversation, thanks y'all :)
