### ISSUE TITLE
Failed to add inspect property to an array

### ISSUE THREAD

**Issue by Wylan** [rails/jbuilder#263]
I am running into an issue when trying to build a top level array as shown in the readme. I'm not sure what I am doing wrong since it looks almost exactly like the example.

```ruby
Jbuilder.new do |json|
  json.array! client_addresses do |address|
    json.street address.street_1
  end
end
```
Using the other syntax for array! results in the same error
```ruby
Jbuilder.new do |json|
  json.array! client_addresses, :street_1
end
```
results in 

```
Jbuilder::ArrayError: Failed to add "inspect" property to an array
```

**Comment by Wylan** [comment]
Upon further testing it seems that is is only an issue in the console. if I do a Jbuilder.encode block around the offending code in the console, I can see that it does indeed add the array of data. I suspect that when testing via the console, inspect is being called and causing the issue.

```ruby 
def address_block
  Jbuilder.new do |json|
    json.array! client_addresses do |address|
      json.street address.street_1
    end
  end
end

Jbuilder.encode do |json|
  json.addresses(address_block)
end
```

```json
 "{"addresses":[{"street":"2917 Harrison St"}]}" 
```

**Comment by rwz** [comment]
Well, here's what happens.

You run the code and it produces a Jbuilder object. Then your console tries to output the result of the last evaluated expression. It takes the objects and calls `inspect` method on it. The calls Jbuilder API and tries to add a new key called `inspect` which fails since you have an array structure that doesn't accept properties.

**Comment by rwz** [comment]
You're right, this is a console-only problem. To work-around this you could try appending `; nil` to the end of your statements. Then it'll be the returned value instead of a Jbuilder object.

Like so:

```ruby
Jbuilder.new do |json|
  json.array! client_addresses, :street_1
end; nil
```

But then you won't be able to see the result of your code. If you want to see the result, use `Jbuilder.encode`.

**Comment by Wylan** [comment]
Thanks for your help, it seems like simply wrapping it in encode is the best way to go when I need to see the output of the code.
