### ISSUE TITLE
Add json.message @message, partial: 'recordings/recording', as: :recording

### ISSUE THREAD

**Issue by dhh** [rails/jbuilder#266]
We currently allow a similar form on collections:

`ruby
json.comments @post.comments, partial: 'comment/comment', as: :comment
`

Would be great to extend that to single objects as well.

**Comment by rwz** [comment]
This unfortunately breaks some backward compatibility. Before the nil value was considered an empty collection, but now we can't automatically imply that, since it could produce confusing results when for instance this code:

```ruby
json.message @message, partial: "message/message", as: :message
```

produces `{ message: [] }`.

I guess we will just make it return `nil`, which is one of the least surprising behaviors. Raising an error would be another alternative. which arguably makes even more sense, preventing the developer to render a partial around nil value.

Thoughts?

**Comment by rwz** [comment]
Anyway, I suspect thhere's a lot of people relying on this nil-collection behavior, and they probably not gonna be happy about this change. :(

**Comment by dhh** [comment]
I think nil = collection is fine to continue with. Passing an object instead of a collection is still very helpful, and unlikely that you're going to pass nil intentionally.

**Comment by rwz** [comment]
> I think nil = collection is fine to continue with. Passing an object instead of a collection is still very helpful, and unlikely that you're going to pass nil intentionally.

Ok, will probably release this later today then.

My main concern was that you'll probably end up doing stuff like:

```ruby
# posts/_post.json.jbuilder
json.author post.author
```

...which will render expected `{ author: [] }`, when `post.author` is nil.

**Comment by dhh** [comment]
Yeah, I dont think that's an issue. Let's just make sure to document it.
