### ISSUE TITLE
helper method not work in jbuilder

### ISSUE THREAD

**Issue by TravisTam** [rails/jbuilder#308]
can anyone help? I have set a helper method on ApplicationHelper and try to make it work on jbuilder. However, it shows
```undefined local variable or method `current_user_detail' ```

this is my ApplicationHelper
```
module ApplicationHelper
  def current_user_detail
    User.find(current_user.id).user_detail if user_signed_in?
  end
end
```

this is my Application controller
```
class ApplicationController <ActionController::API
  include ActionController::ImplicitRender
  include ActionController::Helpers
```

can someone help?

**Comment by rwz** [comment]
Jbuilder is not designed to work with `ActionController::API`. Try inheriting your controllers from `ActionController::Base` instead.

**Comment by betoharres** [comment]
> Jbuilder is not designed to work with `ActionController::API`. Try inheriting your controllers from `ActionController::Base` instead.

This is mindblowing, and at least misleading how rails api adds jbuilder in their default Gemfile saying: 
```
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder'
```
That tricked my into thinking jbuilder could talk to ActionController::API with **ease**
/sad
this should be fixed in my opinion

**Comment by athix** [comment]
Looks like this has been fixed, although I can't call `helper_method` on the API controller on_load because JBuilder hasn't extended the API controller at that point yet...Wondering if I can hook in later in the loading process to extend the API controller with helper methods after it's determined if you're using jbuilder / another implicit renderer for API calls.
