### ISSUE TITLE
Not working with ActionController::API without api_only config set

### ISSUE THREAD

**Issue by morgoth** [rails/jbuilder#328]
My usecase:
* I have rails 5 app that doesn't have `config.api_only` set, because I also have admin panel, so I cannot ditch middlewares
* I'm using `ActionController::API` for my API endpoints altogether with jbuilder

It doesn't work, because action view modules are not included https://github.com/rails/jbuilder/blob/master/lib/jbuilder/railtie.rb#L12-L18 so I have to add them manually.

Do you think we could include them always in Rails 5 app? Not sure if it causes some issues, in case when one uses `ActionController::Base` where this modules are already there.

**Comment by jmbejar** [comment]
Hi @morgoth. In your case, I wouldn't use `ActionController::API` at all.

That's because `ActionController::API` was added to be used in "API only" apps. Apps where you have some controllers inhering from `AC::API` and other from `AC::Base` are not currently supported in Rails.

Given that you don't have `config.api_only` set, using the regular `ActionController::Base` instead of `ActionController::API` seems the best way to already count with the missing action view modules.

**Comment by spastorino** [comment]
It's ok to use `ActionController::API` but you would need to add AV modules by yourself.
Or you could patch make api_only set another flag something like include_av, so api_only = true means include_av = false but you could set include_av = true

**Comment by morgoth** [comment]
ok, thanks. I'll close it then.

**Comment by spastorino** [comment]
@morgoth if you want to go ahead and try to provide a flag to handle all that, it's more than welcome :)

**Comment by morgoth** [comment]
Do you mean flag as a jbuilder config? So you could do something like `Rails.configuration.jbuilder.include_something = true`?

**Comment by spastorino** [comment]
@morgoth don't worry, what I said is also wrong. We are going to provide a different patch for this.

**Comment by jmbejar** [comment]
@morgoth Fixed by following your initial proposal of always adding action view module: https://github.com/rails/jbuilder/commit/64c510ec69d9e63b73ffd5942e802d21a7d14701

**Comment by morgoth** [comment]
Cool, thanks.
