### ISSUE TITLE
Jbuilder partials not rendered automatically

### ISSUE THREAD

**Issue by sambecker** [rails/jbuilder#342]
Unlike view partials in HTML, Jbuilder partials do not output automatically. Is this the intended behavior?

For instance, when a partial exists, shouldn't this,

```
json.array! @models
```

produce the same output as this?

```
json.array! @models do |model|
  json.partial! model
end
```

Forgive me if this has already been discussed or is a larger issue with the Rails framework!

**Comment by ivanovaleksey** [comment]
I am not sure but I think this is intended behaviour.
By the way you can do this
`json.array! @models, partial: 'models/model', as: :model`
so it would use `views/models/_model.json.jbuilder` with `model` variable inside of it.

**Comment by sambecker** [comment]
@ivanovaleksey that makes sense. Thanks for the syntax. It just seems more Rails-like for Jbuilder commands like `json.array! @models` to function similarly to view commands like `render @models` which output a partial for each model in the collection. Does that make sense?

**Comment by ivanovaleksey** [comment]
I am not sure and cannot give you exact answer. On one hand it could make sense but on the other hand `array!` would require more time to render if it had to find whether the partial exists.
Since you can use the syntax above I don't think it is an issue at all. As for explicitly specifying a partial even makes the code clearer.

**Comment by robin850** [comment]
Actually no, this is the intended behavior. `json.array!` either applies the given block to the given collection or tries to convert the collection to an array (which will be rendered as an array in JSON). Your request seems legit since the way `render` works is really idiomatic in Rails but in Jbuilder, the common behavior is to try to convert the object(s) to a JSON representation rather than trying to render a view/partial. You can see this trying to do something like `json.comments article.comments` ; it will render the collection of comments without looking for any partial.

We can give this a close I guess. Thanks for reporting anyway !

**Comment by sambecker** [comment]
Thanks for getting back to me on this @robin850! Totally understand the rationale.
