### ISSUE TITLE
Passing object into partial fails if locals: not used

### ISSUE THREAD

**Issue by yusufali2205** [rails/jbuilder#378]
Passing objects to partial fails if the below format is used:
`json.comments @post.comments, partial: 'comments/comment', as: :comment, show: false`

It succeeds if locals option is used:
`json.comments @post.comments, partial: 'comments/comment', locals: { show: false }, as: :comment`

**Comment by SGospodinov** [comment]
I tried to reproduce the problem by creating these two tests and adding them to the `test/jbuilder_template_test.rb`. They both expect result records to contain `published` attribute.
```ruby
test "render array of partials with locals passed as a hash" do
  result = jbuild(<<-JBUILDER)
    json.array! BLOG_POST_COLLECTION, partial: "blog_post_with_locals", as: :blog_post, locals: { published: true }
  JBUILDER

  assert_equal result[0]["published"], true
end
```
This test pass.

```ruby
test "render array of partials with locals passed as part of the params" do
  result = jbuild(<<-JBUILDER)
    json.array! BLOG_POST_COLLECTION, partial: "blog_post_with_locals", as: :blog_post, published: true
  JBUILDER

  assert_equal result[0]["published"], true
end
```
But this one raises `ActionView::Template::Error: undefined local variable or method 'published'` error.

I'm using the following partial:

```ruby
BLOG_POST_PARTIAL_WITH_LOCALS = <<-JBUILDER
  json.extract! blog_post, :id, :body
  json.author do
    first_name, last_name = blog_post.author_name.split(nil, 2)
    json.first_name first_name
    json.last_name last_name
  end
  json.published published
JBUILDER
```
Which is a slight modification of one of the existing partials in the test file and also should be added to the `PARTIALS` hash. 
I think the problem is caused by the `_render_partial_with_options` method in `JbuilderTemplate`. If this issue is assessed as a bug, I'll be happy to work on it.

**Comment by peret** [comment]
I also just ran into this after upgrading the gem. This definitely looks like a regression to me. Is there any progress on this issue?

**Comment by bobdutch** [comment]
+1

**Comment by arcticleo** [comment]
+1

**Comment by eveevans** [comment]
`json.array! @post.comments, partial: "comments/comment", as: :comment, locals: { show: false }`

**Comment by jeremy** [comment]
#435

**Comment by ngouy** [comment]
What happend to that?

I still have the issue, and I can't access the linked PR (404)
And can't see any specs related to that under tests/template

(And I have the same issue)

**Comment by siegfault** [comment]
@ngouy here's the commit link since the PR link no longer works: https://github.com/rails/jbuilder/commit/91c4eeed484abd28cada2628af1f45f3de0cb0f5. I haven't heard of the issue resurfacing after the fix

**Comment by ngouy** [comment]
@siegfault I have the issue when I do the following (but maybe it's intended this way, or I'm using it wrong):

```rb
# to_do_list partial
json.extract!(to_do_list, :id, :name)

if locals&.dig(:include_relationships)
  json.tasks { json.array!(to_do_list.tasks, partial: "api/tasks/task", as: :task) }
end
```

This one works as expected
```rb
# to_to_list/show

json.partial!(
  "api/to_do_lists/to_do_list",
  to_do_list: @to_do_list,
  locals: { include_relationships: true },
)
```

but if I am to use the partial without enforcing the `locals` variable, I have the described error
```rb
# to_to_list/index

json.array!(@to_do_lists, partial: "api/to_do_lists/to_do_list", as: :to_do_list)
```

Error : `ActionView::Template::Error:
            undefined local variable or method `locals' for #<ActionView::Base:0x00000000036c40>`

Versions:
Rails: 6.1.4
jbuilder: 2.11.2

**Comment by siegfault** [comment]
It's been awhile, but I think this issue was about passing the argument to the method without wrapping it in locals (i.e.
```ruby
json.partial!(
  "api/to_do_lists/to_do_list",
  to_do_list: @to_do_list,
  locals: { include_relationships: true },
)
```
vs.
```ruby
json.partial!(
  "api/to_do_lists/to_do_list",
  to_do_list: @to_do_list,
  include_relationships: true,
)
```
). In your view, I think you want to access the specific local variable rather than the locals keyword:
```diff
  # to_do_list partial
  json.extract!(to_do_list, :id, :name)

- if locals&.dig(:include_relationships)
+ if include_relationships
    json.tasks { json.array!(to_do_list.tasks, partial: "api/tasks/task", as: :task) }
  end
```
but I think you need to pass the argument in either case. For the array case, I think either of the following should work:
```ruby
json.array!(@to_do_lists, partial: "api/to_do_lists/to_do_list", as: :to_do_list, include_relationships: true)
json.array!(@to_do_lists, partial: "api/to_do_lists/to_do_list", as: :to_do_list, locals: { include_relationships: true })
```

**Comment by ngouy** [comment]
@siegfault Yes indeed

The issue was more about this :

If I call the same partial without passing locals (regardless of what I pass in it), the check on the `locals` variable throw an error

If I am to use directly the variable, it kinda make sense that if I don't pass anything like
`json.array!(@to_do_lists, partial: "api/to_do_lists/to_do_list", as: :to_do_list)`
of course I can't call `include_relationships` directly

But I would've expected that the `values` call would just return me an empty hash, rather than raising an error

I don't want to always be explicit and pass empty/nil variables when I don't want the partial to do it's thing

Am I just misunderstanding how `locals` is used?

**Comment by siegfault** [comment]
I'll admit I'm not super familiar with this gem, so it may be worth creating a new issue to get a broader set of eyes on it, but I'll give it a stab.

I think the partial needs to know in some way whether or not to include the relationships. You could be explicit about the partial you use and decide which partial to render at the caller:
```ruby
# to_do_list partial
json.extract!(to_do_list, :id, :name)

# to_do_list_with_relationships partial
json.partial!(
  "api/to_do_lists/to_do_list",
  to_do_list: @to_do_list,
)

json.tasks { json.array!(to_do_list.tasks, partial: "api/tasks/task", as: :task) }
```
If you want to maintain the single partial, you could either check if it's set or default it:
```ruby
  # to_do_list partial
  json.extract!(to_do_list, :id, :name)

  if defined?(:include_relationships) && include_relationships
    json.tasks { json.array!(to_do_list.tasks, partial: "api/tasks/task", as: :task) }
  end

# or
  # to_do_list partial
  include_relationships = false unless defined?(:include_relationships)
  json.extract!(to_do_list, :id, :name)

  if include_relationships
    json.tasks { json.array!(to_do_list.tasks, partial: "api/tasks/task", as: :task) }
  end
```

**Comment by ngouy** [comment]
make complete sense

My point was just something like: Hey, reading the docs, I really had the impression "locals" variable was something special, that would at least return nil or something like that when none are given, rather than raising an issue

Thanks for your help, I will take a look to the direct variable access, not through locals, with `defined?`

Thanks 🙏
