### ISSUE TITLE
ignore_nil has no effect

### ISSUE THREAD

**Issue by mortik** [rails/jbuilder#438]
I tried to add empty objects to my json output like this:

initializer:
```
Jbuilder.ignore_nil false
```
station.jbuilder:
```
json.name station.name
json.planet do
  return json.null! if station.planet.blank?
  json.partial! 'api/v1/stations/planet', planet: station.planet
end
```

I'm expecting to receive the following response when ```station.planet``` is nil:

```
{
  "name": "Deep Space Nine",
  "planet": null
}
```

But this will only return: 

```
{
  "name": "Deep Space Nine"
}
```

if i remove ```json.ignore_nil``` or set it to true nothing changes.

I'm currently using ```2.7.0```

**Comment by vbrazo** [comment]
@mortik what ruby version are you using?

**Comment by mortik** [comment]
@vbrazo 2.5.1p57

**Comment by HappySoft** [comment]
`jbuilder` also skips `false` values (similar to https://github.com/rails/jbuilder/pull/21).

Example (in Rails console):
```
source = <<~JBUILDER
  json.set! :obj do
    json.set! :key1, true
    json.set! :key2, false
  end
JBUILDER

template = ActionView::Template.new(source, 'test', JbuilderHandler, virtual_path: 'test')
puts template.render(self, {})
```
Output:
```
{"obj":{"key1":true}}
```
I reckon this is wrong behaviour. `false` value must be included in the result.

**Comment by robin850** [comment]
Hi @mortik,

The problem is certainly that you are using `return` inside the block ; using `return` stops the execution of the block but doesn't actually yield the value so you should rather use:

~~~ruby
json.planet do
  if station.planet.blank?
    json.null!
  else
    json.partial! 'api/v1/stations/planet', planet: station.planet
  end
end
~~~

You can reproduce this with a simple snippet like this:

~~~ruby
def foo
  yield
end

puts foo { return "Hello" }
~~~

Removing `return` from the block will properly print "Hello". 

Thanks for reporting this anyway !

**Comment by mortik** [comment]
Oh thanks... actually did not know that about blocks :)
